trigger:
  branches:
    include:
    - main
  paths:
    include:
    - .pipeline/apim
    - templates/apim
lockBehavior: runLatest
stages:
- stage: Artifacts
  jobs:
    - job: publish_artifacts
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: PublishBuildArtifacts@1
          displayName: "Pushing deployment artifacts"
          inputs:
            PathtoPublish: "$(Build.Repository.LocalPath)/templates/apim"
            ArtifactName: "drop"
            publishLocation: "Container"

- template: apim-stages.yaml